config/routes.rb
Rails.application.routes.draw do
  resources :worksheets
  root 'worksheets#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem.rb
class Problem < ApplicationRecord

        def self.create_problem_set(worksheet_id:, number_of_problems:)

            number_of_problems.times do |i|
                problem = Problem.create(equation: "x^2+y^2=1", answer: 2)
                WorksheetProblem.create(worksheet_id: worksheet_id, problem_id: problem.id)
            end

        end

end

app/models/worksheet.rb
class Worksheet < ApplicationRecord

    NUMBER_OF_PROBLEMS = 10

    def save
        self.save!
        Problem.create_problem_set(worksheet_id: self.id, number_of_problems: NUMBER_OF_PROBLEMS)
    end

end

app/models/worksheet_problem.rb
class WorksheetProblem < ApplicationRecord
  belongs_to :worksheet
  belongs_to :problem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/worksheets_controller.rb
class WorksheetsController < ApplicationController
  before_action :set_worksheet, only: %i[ show edit update destroy ]

  # GET /worksheets or /worksheets.json
  def index
    @worksheets = Worksheet.all
  end

  # GET /worksheets/1 or /worksheets/1.json
  def show
  end

  # GET /worksheets/new
  def new
    @worksheet = Worksheet.new
  end

  # GET /worksheets/1/edit
  def edit
  end

  # POST /worksheets or /worksheets.json
  def create
    @worksheet = Worksheet.new(worksheet_params)

    respond_to do |format|
      if @worksheet.save
        format.html { redirect_to @worksheet, notice: "Worksheet was successfully created." }
        format.json { render :show, status: :created, location: @worksheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worksheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worksheets/1 or /worksheets/1.json
  def update
    respond_to do |format|
      if @worksheet.update(worksheet_params)
        format.html { redirect_to @worksheet, notice: "Worksheet was successfully updated." }
        format.json { render :show, status: :ok, location: @worksheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worksheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worksheets/1 or /worksheets/1.json
  def destroy
    @worksheet.destroy
    respond_to do |format|
      format.html { redirect_to worksheets_url, notice: "Worksheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worksheet
      @worksheet = Worksheet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worksheet_params
      params.require(:worksheet).permit(:font, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/worksheets_helper.rb
module WorksheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MathMachine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/worksheets/_form.html.erb
<%= form_with(model: worksheet) do |form| %>
  <% if worksheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worksheet.errors.count, "error") %> prohibited this worksheet from being saved:</h2>

      <ul>
        <% worksheet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :font %>
    <%= form.text_field :font %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/worksheets/edit.html.erb
<h1>Editing Worksheet</h1>

<%= render 'form', worksheet: @worksheet %>

<%= link_to 'Show', @worksheet %> |
<%= link_to 'Back', worksheets_path %>

app/views/worksheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Worksheets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worksheets.each do |worksheet| %>
      <tr>
        <td><%= worksheet.name %></td>
        <td><%= link_to 'Show', worksheet %></td>
        <td><%= link_to 'Edit', edit_worksheet_path(worksheet) %></td>
        <td><%= link_to 'Destroy', worksheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worksheet', new_worksheet_path %>

app/views/worksheets/new.html.erb
<h1>New Worksheet</h1>

<%= render 'form', worksheet: @worksheet %>

<%= link_to 'Back', worksheets_path %>

app/views/worksheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Font:</strong>
  <%= @worksheet.font %>
</p>

<%= link_to 'Edit', edit_worksheet_path(@worksheet) %> |
<%= link_to 'Back', worksheets_path %>